version: '3'
services:
 alfresco:
  build: ./alfresco
  links:
   - db
   - share
   - solr4
   - libreoffice
  ports:
   - 8081:8080

 db:
  build: ./postgres
  ports:
   - 5432:5432
  environment:
   - POSTGRES_DB=alfresco
   - POSTGRES_USER=alfresco
   - POSTGRES_PASSWORD=alfresco

 share:
  build: ./share
  ports:
   - 8080:8080

 solr4:
  build: ./solr4
  ports:
   - 8082:8080

 libreoffice:
  image: xcgd/libreoffice
 
