version: "3"
services:
 ora2pg:
    build: ora2pg
    depends_on:
      - postgres
      - oracle11g
    links:
      - postgres
      - oracle11g
    volumes:
      - ./out:/home/ora2pg/workdir/out

 oracle11g:
    build: oracle11g

 postgres:
    build: postgres
    depends_on:
      - oracle11g
    environment:
      - POSTGRES_DB=alfresco
      - POSTGRES_USER=alfresco
      - POSTGRES_PASSWORD=alfresco
